- name: Configure Cisco AP via Telnet
  hosts: ap
  gather_facts: no
  
  tasks:
    - name: Send configuration commands
      ansible.netcommon.telnet:
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        login_prompt: "Username:"
        password_prompt: "Password:"
        prompts:
          - 'ap#'
        commands:
          - configure terminal
          - dot11 ssid 62_Rivan_Steavher
          - vlan 10
          - authentication open
          - authentication key-management wpa
          - wpa-psk ascii Cisc@123
          - guest-mode
          - default interface Dot11Radio 0
          - default interface gigabitethernet 0
          - interface Dot11Radio 0
          - no shutdown
          - channel 9
          - encryption mode ciphers tkip
          - encryption vlan 10 mode ciphers tkip
          - ssid 62_Rivan_Steavher
          - exit
          - interface Dot11Radio 0.10
          - encapsulation dot1q 10 native
          - bridge-group 1
          - exit
          - end
          - write memory
      register: telnet_result

    - name: Show Telnet output
      debug:
        var: telnet_result
