---
- name: Configure VLANs, DHCP Pools, and Interface Ports
  hosts: switch
  gather_facts: no
  connection: network_cli
  
  vars:
    ansible_network_os: ios
    ansible_connection: network_cli
  
  tasks:
    - name: Create VLANs
      ios_config:
        lines:
          - vlan 10
          - name WIFIVLAN
          - vlan 50
          - name IPCCTVLAN
          - vlan 100
          - name VOICEVLAN
      register: result_create_vlans
