---
- name: Configure VLANs, DHCP Pools, and Interface Ports
  hosts: switch  # Replace with the appropriate host or group
  gather_facts: no  # Disable fact gathering for network devices
  become: yes  # Use privilege escalation to execute commands as a privileged user (if needed)

  tasks:
    - name: "Create VLANs"
      cisco.ios.ios_config:
        commands:
          - configure terminal
          - vlan 10
          - name WIFIVLAN
          - exit
          - vlan 50
          - name IPCCTVLAN
          - exit
          - vlan 100
          - name VOICEVLAN
          - exit
