---
- name: Configure VLANs, DHCP Pools, and Interface Ports
  hosts: switch  # Replace with your host/group from inventory
  gather_facts: no  # Not needed for network devices
  connection: network_cli  # Required for network modules
  collections:
    - cisco.ios  # Use the official Cisco IOS collection

  tasks:
    - name: Create VLANs
      cisco.ios.ios_vlans:  # Use the dedicated VLAN module
        config:
          - vlan_id: 10
            name: WIFIVLAN
          - vlan_id: 50
            name: IPCCTVLAN
          - vlan_id: 100
            name: VOICEVLAN
        state: merged  # Ensures VLANs are added if they don't exist
      register: result_create_vlans

    - name: Debug VLAN creation result (optional)
      debug:
        var: result_create_vlans
