---
- name: Configure VLANs, DHCP Pools, and Interface Ports
  hosts: switch
  gather_facts: no
  become: yes

  tasks:
     -name: "Create VLANs"
      ios_command:  # Changed from ios_command to ios_config for configuration changes
        commands:
          - vlan 10
          - name WIFIVLAN
          - vlan 50
          - name IPCCTVLAN
          - vlan 100
          - name VOICEVLAN
